### ISSUE TITLE
Errors Compiling with EDITOR directive.

### ISSUE THREAD

**Issue by SirSwish** [kstuedem/MuckyFoot-UrbanChaos#1]
Trying to see if the in built Editor is still functioning. I have tried compiling with EDITOR pre-processor directive, but this causes a lot of issues.

Looks like Line 4 in "EdUtils.h" is referencing the wrong "Structs.h", but when this is fixed, there are many unresolved external symbols linked to a bunch of .obj files.

```
2>   Creating library .\Debug\Fallen.lib and object .\Debug\Fallen.exp
2>facet.obj : error LNK2001: unresolved external symbol "struct ES_Hi (* ES_hi)[128]" (?ES_hi@@3PAY0IA@UES_Hi@@A)
2>GEdit.obj : error LNK2001: unresolved external symbol "public: static bool RenderState::AllowFadeOut" (?AllowFadeOut@RenderState@@2_NA)
2>Anim.obj : error LNK2001: unresolved external symbol "struct KeyFrameChunk edit_chunk1" (?edit_chunk1@@3UKeyFrameChunk@@A)
2>Anim.obj : error LNK2001: unresolved external symbol "struct KeyFrameElement * elements_bank1" (?elements_bank1@@3PAUKeyFrameElement@@A)
2>Anim.obj : error LNK2001: unresolved external symbol "struct KeyFrameElement * elements_bank2" (?elements_bank2@@3PAUKeyFrameElement@@A)
```
.....

etc.

Any thoughts how these may be resolved? I don't use VS a lot, so not sure if this is just some missed configuration or what. :(

**Comment by kstuedem** [comment]
Sorry for the late reply. The EDITOR directive is completly broken. But that's not really surprising as the game itself already has plently of issues. The problem here is that the original source release isn't for the PC Version but some intermediate version in the rather destructive porting process for the Dreamcast.
I think in earlier version the game didn't immediately crash when selecting "EDITOR" from the main menu and you could even see some UI. But I might misremember things. Anyway getting the editor to actually work would likely be a lot of work and even then there still might be some resource files missing that weren't in the shipped game files.

**Comment by SirSwish** [comment]
Ah I see. I was wondering why there was PSX and Dreamcast (DC) mentioned all throughout this code. Now it makes sense. I figured it was all developed in the same 'parent' code base initially then exported with different directives as needed for each system. That makes sense as all the UI elements appear to be visible in the code, but as you say functionality might be a different story. I'll continue trying to resolve the issues, but I don't have high hopes. Thanks, Kai.

- Swish
